/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as CanvasRouteImport } from './routes/canvas'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CanvasIndexRouteImport } from './routes/canvas.index'
import { Route as CanvasWorkflowIdRouteImport } from './routes/canvas.$workflowId'

const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const CanvasRoute = CanvasRouteImport.update({
  id: '/canvas',
  path: '/canvas',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CanvasIndexRoute = CanvasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CanvasRoute,
} as any)
const CanvasWorkflowIdRoute = CanvasWorkflowIdRouteImport.update({
  id: '/$workflowId',
  path: '/$workflowId',
  getParentRoute: () => CanvasRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/canvas': typeof CanvasRouteWithChildren
  '/projects': typeof ProjectsRoute
  '/canvas/$workflowId': typeof CanvasWorkflowIdRoute
  '/canvas/': typeof CanvasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/projects': typeof ProjectsRoute
  '/canvas/$workflowId': typeof CanvasWorkflowIdRoute
  '/canvas': typeof CanvasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/canvas': typeof CanvasRouteWithChildren
  '/projects': typeof ProjectsRoute
  '/canvas/$workflowId': typeof CanvasWorkflowIdRoute
  '/canvas/': typeof CanvasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/canvas' | '/projects' | '/canvas/$workflowId' | '/canvas/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/projects' | '/canvas/$workflowId' | '/canvas'
  id:
    | '__root__'
    | '/'
    | '/canvas'
    | '/projects'
    | '/canvas/$workflowId'
    | '/canvas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CanvasRoute: typeof CanvasRouteWithChildren
  ProjectsRoute: typeof ProjectsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/canvas': {
      id: '/canvas'
      path: '/canvas'
      fullPath: '/canvas'
      preLoaderRoute: typeof CanvasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/canvas/': {
      id: '/canvas/'
      path: '/'
      fullPath: '/canvas/'
      preLoaderRoute: typeof CanvasIndexRouteImport
      parentRoute: typeof CanvasRoute
    }
    '/canvas/$workflowId': {
      id: '/canvas/$workflowId'
      path: '/$workflowId'
      fullPath: '/canvas/$workflowId'
      preLoaderRoute: typeof CanvasWorkflowIdRouteImport
      parentRoute: typeof CanvasRoute
    }
  }
}

interface CanvasRouteChildren {
  CanvasWorkflowIdRoute: typeof CanvasWorkflowIdRoute
  CanvasIndexRoute: typeof CanvasIndexRoute
}

const CanvasRouteChildren: CanvasRouteChildren = {
  CanvasWorkflowIdRoute: CanvasWorkflowIdRoute,
  CanvasIndexRoute: CanvasIndexRoute,
}

const CanvasRouteWithChildren =
  CanvasRoute._addFileChildren(CanvasRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CanvasRoute: CanvasRouteWithChildren,
  ProjectsRoute: ProjectsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
