import type { PricingRule } from '@mina/contracts/modules/pricing'

export interface PricingRepository {
  listRules(): Promise<PricingRule[]>
}

const nowIso = new Date('2026-01-01T00:00:00.000Z').toISOString()

export const createDefaultPricingRules = (): PricingRule[] => [
  {
    id: 'price_image_dev_image',
    taskKind: 'image_generation',
    provider: 'dev',
    model: 'dev-image',
    billingMetric: 'image',
    unitPrice: 1,
    currency: 'credit',
    activeFrom: nowIso,
    priority: 10,
  },
  {
    id: 'price_video_720p_duration',
    taskKind: 'video_generation',
    provider: 'dev',
    model: 'dev-video',
    pricingKey: 'resolution:720p',
    billingMetric: 'duration_second',
    unitPrice: 5,
    currency: 'credit',
    activeFrom: nowIso,
    priority: 20,
  },
  {
    id: 'price_video_1080p_duration',
    taskKind: 'video_generation',
    provider: 'dev',
    model: 'dev-video',
    pricingKey: 'resolution:1080p',
    billingMetric: 'duration_second',
    unitPrice: 10,
    currency: 'credit',
    activeFrom: nowIso,
    priority: 30,
  },
  {
    id: 'price_google_gemini_flash_image_1k',
    taskKind: 'image_generation',
    provider: 'google',
    model: 'gemini-3.1-flash-image-preview',
    pricingKey: 'size:1K',
    billingMetric: 'image',
    unitPrice: 1,
    currency: 'credit',
    activeFrom: nowIso,
    priority: 10,
  },
  {
    id: 'price_google_gemini_pro_image_1k',
    taskKind: 'image_generation',
    provider: 'google',
    model: 'gemini-3-pro-image-preview',
    pricingKey: 'size:1K',
    billingMetric: 'image',
    unitPrice: 2,
    currency: 'credit',
    activeFrom: nowIso,
    priority: 10,
  },
  {
    id: 'price_google_veo_preview_720p_duration',
    taskKind: 'video_generation',
    provider: 'google',
    model: 'veo-3.1-generate-preview',
    pricingKey: 'resolution:720p',
    billingMetric: 'duration_second',
    unitPrice: 10,
    currency: 'credit',
    activeFrom: nowIso,
    priority: 10,
  },
  {
    id: 'price_google_veo_fast_720p_duration',
    taskKind: 'video_generation',
    provider: 'google',
    model: 'veo-3.1-fast-generate-preview',
    pricingKey: 'resolution:720p',
    billingMetric: 'duration_second',
    unitPrice: 6,
    currency: 'credit',
    activeFrom: nowIso,
    priority: 10,
  },
  {
    id: 'price_volcengine_seedream_50_2048',
    taskKind: 'image_generation',
    provider: 'volcengine',
    model: 'doubao-seedream-5-0-260128',
    pricingKey: 'size:2048x2048',
    billingMetric: 'image',
    unitPrice: 1,
    currency: 'credit',
    activeFrom: nowIso,
    priority: 10,
  },
  {
    id: 'price_volcengine_seedream_45_2048',
    taskKind: 'image_generation',
    provider: 'volcengine',
    model: 'doubao-seedream-4-5-251128',
    pricingKey: 'size:2048x2048',
    billingMetric: 'image',
    unitPrice: 1,
    currency: 'credit',
    activeFrom: nowIso,
    priority: 10,
  },
  {
    id: 'price_volcengine_seedance_20_720p_duration',
    taskKind: 'video_generation',
    provider: 'volcengine',
    model: 'doubao-seedance-2-0-260128',
    pricingKey: 'resolution:720p',
    billingMetric: 'duration_second',
    unitPrice: 5,
    currency: 'credit',
    activeFrom: nowIso,
    priority: 10,
  },
  {
    id: 'price_volcengine_seedance_15_720p_duration',
    taskKind: 'video_generation',
    provider: 'volcengine',
    model: 'doubao-seedance-1-5-pro-251215',
    pricingKey: 'resolution:720p',
    billingMetric: 'duration_second',
    unitPrice: 7,
    currency: 'credit',
    activeFrom: nowIso,
    priority: 10,
  },
  {
    id: 'price_volcengine_lumina_j_720p_duration',
    taskKind: 'video_generation',
    provider: 'volcengine',
    model: 'jimeng-video-seedance-2.0',
    pricingKey: 'resolution:720p',
    billingMetric: 'duration_second',
    unitPrice: 5,
    currency: 'credit',
    activeFrom: nowIso,
    priority: 10,
  },
  {
    id: 'price_volcengine_lumina_j_fast_720p_duration',
    taskKind: 'video_generation',
    provider: 'volcengine',
    model: 'jimeng-video-seedance-2.0-fast',
    pricingKey: 'resolution:720p',
    billingMetric: 'duration_second',
    unitPrice: 4,
    currency: 'credit',
    activeFrom: nowIso,
    priority: 10,
  },
]
